Декоративные элементы главной
htmlacademy-adaptive/1756361-sedona-25 pull request #7
Opened 2022-05-04 14:43 UTC by drmisssciurus

2022-05-04 19:25 UTC, oksanych requested changes

2022-05-04 19:25 UTC, oksanych commented on source/less/blocks/map.less
> +  margin-top: 42px;
Лучше сокращать margin: 42px auto 0;

2022-05-04 19:25 UTC, oksanych commented on source/less/blocks/qestions.less
> +  padding-top: 39px;
padding: 39px 20px 0;

2022-05-05 19:05 UTC, drmisssciurus commented on source/less/blocks/map.less
> +  margin-top: 42px;
<img width="367" alt="Снимок экрана 2022-05-05 в 22 03 45" src="https://user-images.githubusercontent.com/81309298/167006082-9eaadd53-0c00-4f66-ac49-d0d8c6907c87.png">

при таком написание выставляется не совсем то что мне нужно

2022-05-06 16:11 UTC, merged